server:
  port: 8081
# DataSource Config
spring:
  profiles:
    active: dev
  application:
    name: mymall-admin
#  security:
#    user:
#      name: user
#      password: 111111

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml

atguigu:
  jwt:
    header: Authorization
    expire: 604800 #7天，秒单位
    secret: ji8n3439n439n43ld9ne9343fdfer49h
