server:
  port: 8084
# DataSource Config
spring:
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  session:
    store-type: redis
  profiles:
    active: dev
  application:
    name: mymall-member
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
