server:
  port: 8082
# DataSource Config
spring:
  profiles:
    active: dev
  application:
    name: mymall-product
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
