server:
  port: 8082
# DataSource Config
spring:
  profiles:
    active: dev
  application:
    name: mymall-product
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0

#配置自定义的线程池
mymall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10




