spring:
  application:
    name: mymall-gateway
  cloud:
    gateway:
#      网关直接把authorization响应头给去了。。。。
      routes:
        - id: admin-route
          uri: lb://mymall-admin
          predicates:
            - Path=/api/admin/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: product-route
          uri: lb://mymall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: third-party-route
          uri: lb://mymall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>.*),/$\{segment}

server:
  port: 88

