server:
  port: 8086
# DataSource Config
spring:
  profiles:
    active: dev
  application:
    name: mymall-ware
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
