server:
  port: 8086
# DataSource Config
spring:
  rabbitmq:
    host: 127.0.0.1
    listener:
      simple:
        acknowledge-mode: manual
  profiles:
    active: dev
  application:
    name: mymall-ware
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
