spring:
  session:
    store-type: redis
  application:
    name: mymall-auth
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  redis:
    password: 123456
server:
  port: 20000

