server:
  port: 8085
# DataSource Config
spring:
  cache:
    type: redis
    redis:
      time-to-live: 3600000
      use-key-prefix: true
      cache-null-values: true
  session:
    store-type: redis
  profiles:
    active: dev
  application:
    name: mymall-order
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
#配置自定义的线程池
mymall:
  thread.core-size: 20
  thread.max-size: 200
  thread.keep-alive-time: 10
